TESTSET_ENABLE: False
OUTPUT_DIR: './work_dirs/paper-setting'
MODEL:
  WEIGHT: './work_dirs/pretrained/resnet-50_rename.pth'
SOLVER:
  OPTIMIZER: 'Adam'
  IMS_PER_GPU: 32
  BASE_LR: 4e-3
  CHECKPOINT_PERIOD: 2400
  GAMMA: 0.5
  MAX_ITER: 96000
  SCHEDULER: 'linear'
  WARMUP_ITERS: 2400
TEST:
  IMS_PER_GPU: 8